export const ApiRoutes = {
  API_HOSTNAME: "http://localhost:8080/",
  INSERTJOB: "insertjob",
  APPLYJOB: "applyjob",
  UPDATEPROFILE: "updateprofile",
  GETCATEGORY: "get-category",
  GETSALARY: "get-salary",
  GETJOBTYPE: "get-jobtype",
  GETEXPERIENCE: "get-experience",
  GETGENDER: "get-gender",
  GETINTERVIEW: "get-interview",
  GETJOB: "get-job",
  GETJOBB: "get-jobb",

  GETJOBD: "get-jobd",
  GETJOBM: "get-jobm",
  INSERT: "insert",
  INSERTREC: "insertrec",
  LOGIN: "login",
  LOGINREC: "loginrec",
  GETREGISTRAION: "get-registration",
  CONTACTUS: "contactus",
  CONTACTUSR: "contactusr",
  GETWORKINGTIME: "get-working-time",
  UPDATECOMPANY: "updatecompany",
  GETCOMPANY: "get-company",
  GETREC: "get-rec",
  GETPWD: "get-pwd",
  CHANGEPWD: "changepwd",
  CHANGERPWD: "changerpwd",
  DELETEJOB: "deletejob",
  UPDATEJOB: "updatejob",
  GETADDJOB: "get-addjob",
  REVIEW: "review",
  REVIEWR: "reviewr",
  UPDATECATEGORY: "updatecategory",
  DELETECATEGORY: "deletecategory",
  GETAPPLY: "get-apply",
  OTPREQUEST: "otprequest",
  VERIFYOTP: "verify-otp",
  SETNEWPASSWORD: "set-newpassword",
  OTPREQUESTR: "otprequestr",
  VERIFYOTPR: "verify-otpr",
  SETNEWPASSWORDR: "set-newpasswordr",
  DOWNLOADINVOICE:"downloadInvoice",
  DOWNLOADINVOICE1:"downloadInvoice1",
GETPAYMENT:"get-payment",
  PAYMENT:"payment",
  DELETES:"deletes",
  DELETER:"deleter"
};
